-- Pipeline Snapshots Table
-- Stores the full intelligence pipeline snapshot (transfers, pharmacy supplies, orders, adjustments)
-- generated by the review pipeline wizard. Only the most recent snapshot is active;
-- older snapshots are retained for audit purposes.
--
-- The pipeline has a 7-day cooldown: within the cooldown period, the cached snapshot
-- is returned instead of regenerating. This ensures the pharmacist works through a
-- stable, fixed plan based on consistent data.

CREATE TABLE IF NOT EXISTS pipeline_snapshots (
  id            SERIAL PRIMARY KEY,
  snapshot      JSONB NOT NULL,
  generated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  generated_by  INT4 REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_pipeline_snapshots_generated_at
  ON pipeline_snapshots (generated_at DESC);
